### ISSUE TITLE
Incompatible with PyPy

### ISSUE THREAD

**Issue by dan-blanchard** [ParallelSSH/ssh2-python#16]
__Steps to reproduce:__

1. Try to `pip install ssh2-python` from a PyPy interpreter.
2. [Build will fail](https://travis-ci.org/Parsely/streamparse/jobs/317128919#L615-L678):

```
  cc -O2 -fPIC -Wimplicit -Ilibssh2/include -I/home/travis/virtualenv/pypy-5.4.1/include -c pssh/native/ssh2.c -o build/temp.linux-x86_64-2.7/pssh/native/ssh2.o -O3
  pssh/native/ssh2.c:845:3: error: unknown type name ‘PyBaseExceptionObject’
     PyBaseExceptionObject __pyx_base;
     ^
  pssh/native/ssh2.c:857:3: error: unknown type name ‘PyBaseExceptionObject’
     PyBaseExceptionObject __pyx_base;
     ^
  pssh/native/ssh2.c:917:3: error: unknown type name ‘PyBaseExceptionObject’
     PyBaseExceptionObject __pyx_base;
     ^
  pssh/native/ssh2.c:929:3: error: unknown type name ‘PyBaseExceptionObject’
     PyBaseExceptionObject __pyx_base;
     ^
  pssh/native/ssh2.c:941:3: error: unknown type name ‘PyBaseExceptionObject’
     PyBaseExceptionObject __pyx_base;
     ^
  pssh/native/ssh2.c:953:3: error: unknown type name ‘PyBaseExceptionObject’
     PyBaseExceptionObject __pyx_base;
     ^
  pssh/native/ssh2.c:965:3: error: unknown type name ‘PyBaseExceptionObject’
     PyBaseExceptionObject __pyx_base;
     ^
  pssh/native/ssh2.c:976:3: error: unknown type name ‘PyBaseExceptionObject’
     PyBaseExceptionObject __pyx_base;
     ^
  error: command 'cc' failed with exit status 1
```

__Expected behaviour:__ Install would succeed.

__Actual behaviour:__ Compile failed as above.

__Additional info:__ libssh2 1.4.3, Ubuntu 14.04, gcc 4.8.4, PyPy 5.4.1

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest and the report. The above error is actually from `parallel-ssh`, but both projects have same issue building on pypy. This is fixed in latest master branches for both projects, releases pending some travis CI issues.

Note that `parallel-ssh` is not supported on libssh2 < 1.6. `ssh2-python` by itself works with caveats for known issues on old versions like lack of thread safety. You will need to install a recent version of `libssh2` if wanting to use parallel-ssh on pypy, though it builds without errors if just for CI purposes. For production use I'd also recommend PyPy >= 5.9 as its C-API performance [has improved a lot](https://morepypy.blogspot.com/2017/10/pypy-v59-released-now-supports-pandas.html).

Also, PyPy does not support [distributable wheels](https://bitbucket.org/pypy/pypy/issues/2617/) yet so no binary wheels are built for pypy. CPython wheels include libssh2 and other dependencies for both `parallel-ssh` and `ssh2-python` on all platforms.

**Comment by pkittenis** [comment]
New versions with this fix published for both projects, including binary wheels for all (CPython) platforms.

**Comment by dan-blanchard** [comment]
@pkittenis Awesome! Thanks!
