### ISSUE TITLE
sftp open handle failures do not raise exceptions

### ISSUE THREAD

**Issue by boneyard93501** [ParallelSSH/ssh2-python#20]
ran into that today. looks like a libssh2 issue and ru-ssh2 has the same issue. paramiko is fine.
<pre>
standard chroot setup on Ubuntu 16.04 LTS:
Match group sftponly
    ChrootDirectory /home/%u
    X11Forwarding no
    AllowTcpForwarding no
    ForceCommand internal-sftp
</pre>

test code:
<pre>
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import socket
from ssh2.session import Session

CHROOT_DIR = 'CHROOT_DIR'
CHROOT_UNAME = 'CHROOT_UNAME'
CHROOT_PASSWD = 'CHROOT_PASSWD'
ADMIN_UNAME = 'ADMIN_UNAME'
ADMIN_PASSWD = 'ADMIN_PASSWD'

host = 'CHROOTED_HOST'

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.connect((host, 22))
sess = Session()
sess.handshake(sock)
sess.userauth_password(ADMIN_UNAME,ADMIN_PASSWD)
# or
# sess.userauth_password(CHROOT_UNAME,CHROOT_PASSWD)
sftp = sess.sftp_init()
with sftp.opendir(CHROOT_DIR) as fd:
    for size, buf, attrs in fd.readdir():
        print(f'{size},{buf},{attrs}')
</pre>

output:
<pre>
admin group user:
1,b'.',<ssh2.sftp_handle.SFTPAttributes object at 0x1039764c8>
2,b'..',<ssh2.sftp_handle.SFTPAttributes object at 0x1039764e0>
11,b'CHROOTED_DIR',<ssh2.sftp_handle.SFTPAttributes object at 0x1039764c8>

chrooted user (the error from ru-ssh2 is nearly as cryptic):
Traceback (most recent call last):
  File "py_ssh2_test.py", line 22, in <module>
    with sftp.opendir(CHROOT_DIR) as fd:
AttributeError: __enter__
</pre>

**Comment by pkittenis** [comment]
Hi there,

Thank you for the interest and report.

The unhelpful error is because `opendir` call is failing, probably because `CHROOT_DIR` either does not exist or login user has no permissions to read it or the chroot dir. There should be exceptions raised in these cases but there are not yet.

This works for me in a chroot for reading the login dir, the chroot's `/`:

```
with sftp.opendir('.') as fd:
    for size, buf, attrs in fd.readdir():
        print(f'{size},{buf},{attrs}')
```
`opendir('/')` also works.

Can check that `opendir` does not return `None` for now, or try/except the attribute error. Next version will raise exceptions on sftp handle errors.

**Comment by boneyard93501** [comment]
got it. thank you very much.

**Comment by pkittenis** [comment]
Release in `0.11.0.post1`
