### ISSUE TITLE
Failed at ssh2-python after run the exe files which build by pyinstaller

### ISSUE THREAD

**Issue by harte2018** [ParallelSSH/ssh2-python#21]
Hello,

   May I have a question. I met issue after used ssh2-python lib when run the exe file which using pyinstaller to build one.  with the error info "ImportError: No module named 'ssh2.agent'".
   Any suggestion are welcome.

Best Regards,
Harte

  File "main.py", line 13, in <module>
  File "D:\Python34\lib\site-packages\pyinstaller-3.3.1-py3.4.egg\PyInstaller\lo
ader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "SSHcm.py", line 30, in <module>
  File "D:\Python34\lib\site-packages\pyinstaller-3.3.1-py3.4.egg\PyInstaller\lo
ader\pyimod03_importers.py", line 714, in load_module
    module = loader.load_module(fullname)
  File "ssh2\agent.pxd", line 24, in init ssh2.session
ImportError: No module named 'ssh2.agent'
[13140] Failed to execute script main

**Comment by harte2018** [comment]
Get support from PyInstaller team that:
This looks like ssh2\agend.pxd being a Cython file, which PyInstaller can not analyse.
Any workaround are very appreciate ! It will benefit all the user who use the ssh2-python.
And wish enhance can from our ssh2-python owner to support PyInstaller in the future.

**Comment by harte2018** [comment]
Or help to summit a “hook” file to PyInstaller team official way from ssh2-python owner view.

**Comment by harte2018** [comment]
Information here:
ssh2-python (0.10.0)
pyinstaller-pyinstaller-v3.3.1 or later

**Comment by harte2018** [comment]
Hook file link: https://pyinstaller.readthedocs.io/en/latest/hooks.html

**Comment by harte2018** [comment]
Hello, any feedback ? or ssh2-python has no maintenance.

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest.

Can you share steps to reproduce? It is unlikely there is anything that can be done in `ssh2-python` for this, but some workaround from pyinstaller for libraries including native code extensions could be provided.

Pyinstaller should be trying to load the generated `.so` files (ssh2/agent.so) rather than pxd which is only used by cython. That it is not points to the extension modules not being built correctly by pyinstaller in addition to cython library being bundled in the installer which is not required. 

I'd suggest looking at existing pyinstaller files for other libraries with native extension modules to see how they handle it. Regrettably I have no experience with pyinstaller myself to make any suggestions.

**Comment by pkittenis** [comment]
The [information](http://pyinstaller.readthedocs.io/en/latest/feature-notes.html?highlight=cython#cython-support) at [pyinstaller docs](http://pyinstaller.readthedocs.io/en/latest/advanced-topics.html?highlight=cython#the-tree-class) looks relevant - it suggests to exclude `['*.pyx', '*.pxd']` files from being bundled. These are cython source files and are not required for bundled installations.

**Comment by pkittenis** [comment]
This is a 'how to use pyinstaller' question rather than a code issue with `ssh2-python`. In any case, it looks like pyinstaller is not able to figure out the modules it needs to include and they need to be specified manually.

Add them to hidden imports in the specfile:

`hiddenimports=['ssh2.agent', 'ssh2.pkey', 'ssh2.exceptions', 'ssh2.sftp', 'ssh2.sftp_handle', 'ssh2.channel', 'ssh2.listener', 'ssh2.statinfo', 'ssh2.knownhost', 'ssh2.error_codes', 'ssh2.fileinfo', 'ssh2.utils', 'ssh2.publickey'],`

This works on the examples in the repository, eg:

```
pyinstaller example_echo.spec
<..>

./example_echo
['publickey', 'password']
[<ssh2.pkey.PublicKey object at 0x7f010ef35198>, <ssh2.pkey.PublicKey object at 0x7f010ef351b0>, <ssh2.pkey.PublicKey object at 0x7f010ef351c8>, <ssh2.pkey.PublicKey object at 0x7f010ef351e0>]
1004469970
Exit status: 0
me
```

Anything else will have to refer to pyinstaller docs and information. In future these type of questions are better asked on the [mailing group](https://groups.google.com/forum/#!forum/ssh2-python).
