### ISSUE TITLE
Error during import of Session

### ISSUE THREAD

**Issue by Trek333** [ParallelSSH/ssh2-python#38]
### Bug reports

__Steps to reproduce:__

1. Example code that produces error.
from ssh2.session import Session

2. Stack trace or error messages.
<msg type="ERROR">Error starting: /usr/lib64/python2.7/site-packages/ssh2/session.so: undefined symbol: PyUnicodeUCS4_DecodeUTF8</msg>

__Expected behaviour:__ [What was expected to happen.]
Session to be imported

__Actual behaviour:__ [What actually happened.]
see error above

__Additional info:__ [Include version of ``libssh2`` and any other relevant information.]
sys.path = ['/opt/splunk/lib/python2.7/site-packages/splunk/persistconn', '/opt/splunk/lib/python2.7/site-packages', '/opt/splunk/lib/python27.zip', '/opt/splunk/lib/python2.7', '/opt/splunk/lib/python2.7/plat-linux2', '/opt/splunk/lib/python2.7/lib-tk', '/opt/splunk/lib/python2.7/lib-old', '/opt/splunk/lib/python2.7/lib-dynload', '/opt/splunk/etc/apps/cliauto/bin', '/opt/splunk/etc/apps/cliauto/bin/cliautolib', '/usr/lib64/python2.7/site-packages']

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest and report. This is a built from source installation, right?

This error happens when a python built with 4-byte unicode support is attempted to be loaded into a python built with 2-byte unicode support (the default). It is even mentioned in the [official python FAQ](https://docs.python.org/2.7/faq/extending.html#when-importing-module-x-why-do-i-get-undefined-symbol-pyunicodeucs2).

It is 100% not installed from the PyPi binary wheels as pip will not install an incompatible version. There are also both [cp27m](https://files.pythonhosted.org/packages/2b/b3/c4149b630a1b0e32fce41224ef958aba0cbc830a4dfc793f34fa1f3e0431/ssh2_python-0.15.0.post9-cp27-cp27m-manylinux1_x86_64.whl) and [cp27mu](https://files.pythonhosted.org/packages/ce/9d/1f4757274dc15964f228ec119716d720747f4ae0bf3c8e1a5a78390e8f0b/ssh2_python-0.15.0.post9-cp27-cp27mu-manylinux1_x86_64.whl) linux wheels published on PyPi which can be used directly with `pip install ssh2-python`. 

For builds from source, it is the responsibility of the builder to ensure it is used in the python it was built from. It is not an issue with the library.
