### ISSUE TITLE
Shell usage last read hang

### ISSUE THREAD

**Issue by HenGold** [ParallelSSH/ssh2-python#50]
HI
i tried to use execute but i figure out that execute is for single command
i need to run continues commands without initiate new session each time
i tried to use read/write cycles but the read hang on the last iteration

code:
```
        self.ssh_session.flush()
        self.ssh_session.write(cmd + '\n')
        if delay > 0:
            time.sleep(delay)
        size, data = self.ssh_session.read()
        while size > 0:
            self.report.debug(data)
            size, data = self.ssh_session.read()
        return data
```

Thanks

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest. Issue tracker is for bugs/feature requests with the code, this is better asked on the mail group.

`execute` requires a new channel (not session) for each command. [Interactive shell](https://ssh2-python.readthedocs.io/en/latest/channel.html#ssh2.channel.Channel.shell) can be used instead, though execute cannot be used in the case, will have to read/write from shell manually.

If you are looking for a higher level client, see [paralell-ssh](https://github.com/ParallelSSH/parallel-ssh).

**Comment by HenGold** [comment]
Hi 
i know that shell require read/write cycle
but the last read hang.. this is all about

do you suggest to use paralell-ssh?

**Comment by pkittenis** [comment]
The read hangs because there is no more data to be read. On interactive channels no EOF is sent by server to indicate channel has finished. That is expected behaviour of the API in blocking mode. Will need to check if there is anything pending to be read presumably by either `Session.block_directions` or `Channel.poll_read` - haven't tried it.

This project is a wrapper to libssh2, similar code is needed to use it directly as for using libssh2. There are not examples for doing everything not even for libssh2 C code. PRs welcome.

If a more higher level client is what is needed, see `parallel-ssh`. It has both parallel and single host high level clients based on this project.

**Comment by HenGold** [comment]
Thanks!
