### ISSUE TITLE
Can't run ssh2-python with python3-dbg

### ISSUE THREAD

**Issue by kddubb** [ParallelSSH/ssh2-python#59]
### Bug reports

__Steps to reproduce:__
* Install python3-dbg in addition to the standard python installation.
* Run the python3-dbg command line
* Try to import ssh2.session and see that it fails

1. Example code that produces error.
```
hgst@BUILD:~/src/nile$ python3-dbg 
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ssh2.session import Session
```

2. Stack trace or error messages.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'ssh2.session'
>>> 
```

__Expected behaviour:__ [What was expected to happen.]

ssh2-python should work in a python3-dbg environment.

__Actual behaviour:__ [What actually happened.]

An import error is thrown.  My guess is that the dbg version of python is expecting access to the debug symbols of the underlying libssh2 library which aren't included (as far as I can tell).

__Additional info:__ [Include version of ``libssh2`` and any other relevant information.]

Unfortunately, part of the reason I need this is that I'm trying to debug core dumps causes by memory corruption using ssh2-python.  My guess is that I'm not cleaning up properly, but it's hard to pinpoint the issue when the coredumps are obfuscated libssh2 libraries.

Thanks for looking at this!

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest.

python3-dbg is a different python installation - it will need to be installed in there as well. There are no wheels provided for that so will have to install from source (and that requires development headers etc). See from [source installation instructions here](https://ssh2-python.readthedocs.io/en/latest/installation.html#installation-from-source). 

This is not an issue with the code, and it is not possible to support every interpreter out there out of the box - hence the from source installation instructions.

If code can be provided to reproduce a crash then can take a look at that. Failing that, not much that can be done.

**Comment by kddubb** [comment]
OK, I guess I don't understand exactly what is different in python3-dbg yet.  It just seemed odd to me that pretty much every other package I was using seemed to be happy with python3-dbg and ssh2-python wasn't.   I can install from source if necessary and figure out what's going on.

**Comment by pkittenis** [comment]
Pure python packages work across interpreters. Native code extensions (like this one), do not. python3-dbg is a different interpreter.

In any case, I do not see how that would help debug ssh2-python since it's for debugging python stdlib implementations and has no hooks to third party libraries, but as you wish. You might be better off enabling debug mode in a from source libssh2 build.

With no code to reproduce a bug nothing to do here - closing. Feel free to raise a new issue when able to reproduce.

**Comment by kddubb** [comment]
@pkittenis Thanks for the explanation.  If you don't mind I'd like to make this a learning experience for me as I'm a bit out of my element.  

Basically, I am implementing a devops test tool that needs to execute ssh commands on various systems in our emulation and lab setups.  I implemented everything just by putting together ssh commands in subprocess calls.  Obviously there's a better way and I chose ssh2-python to re-implement the tools.  Everything worked well in our basic emulation environment, but as I added the more complex environments I had consistent core dumps during our test runs generally with a message something like "double free or memory corruption".  Without python3-dbg, how would I go about debugging this.  I saw the .so files in the python dist-packages directory for ssh2-python so I assumed you weren't using natively installed libraries, but maybe that was a bad assumption.  I did install libssh2-1-dev (which I think installs libssh2-1-dbg) but it didn't seem to make a difference.

Thanks for listening this far ;)  Any tips on better ways to debug this type of error?

Thanks in advance...and thanks for developing ssh2-python!

**Comment by pkittenis** [comment]
Per above, installation [source instructions](https://ssh2-python.readthedocs.io/en/latest/installation.html#installation-from-source) has information regarding libssh2 and how to build.

> Source distributions include a bundled libssh2 which is built automatically by default. OpenSSL development libraries are required.
> 
> For builds against system provided libssh2, the SYSTEM_LIBSSH2=1 environment variable setting can be used.

For the other questions, again without code to reproduce cannot say and this is an issue tracker, not a Q&A forum. Given there is existing code using both threads and non-blocking mode for parallelisation of ssh2-python which do not cause crashes, it is more likely they are being caused by improper use rather than a bug. As a guess, sessions/channels might be shared across threads which is unsupported by libssh2 and will cause crashes.

For this use case I will point to [parallel-ssh](https://github.com/ParallelSSH/parallel-ssh) which is designed exactly for executing SSH commands across multiple hosts and uses ssh2-python.

**Comment by kddubb** [comment]
@pkittenis  Thanks for indulging me a bit.  Actually, I think you answered the ultimate question which is that I was using ssh2-python wrong as I assumed it was thread safe at least across the session.  That was likely the issue.  I will take a look at parallel-ssh.  Thanks again for the extra responses (even though this isn't a Q&A forum).
